### PR TITLE
My first attempt to add a NL version

### PR DESCRIPTION
**Pull request by moorlag**

### CODE REVIEW

**Comment by moorlag** [comment]
Added the NL version of this marvelous project.

**Comment by gjtorikian** [comment]
Hi @moorlag! I had a chance to look at this. In general, it looks ok, but there seems to be something wrong with where the files are stored. Everything in the main (root) directory has been deleted, and moved into a _public_ subfolder. For example, `_assets/js/lessons.js` was moved to `public/_assets/js/lessons.js`.

Could you restore the file locations where they were? I can do this myself, but, then your name will not show up in the git contributions and I think it's important for contributors to get credit!

**Comment by moorlag** [comment]
Hey @gjtorikian! 
It seems the problem is now resolved. Thanks for the contribution offer :-) 
The local installation doesn't run, I've tried to run it without the problem plugins; thus the root -> public. 
Is the problem now resolved? 

Perhaps we can add a contribution list, always fun to see it during an job interview when they Google'ed someone.

**Comment by gjtorikian** [comment]
Thanks for this! I ended up cherry picking your commits, fixing the build, and merging them in https://github.com/gjtorikian/markdowntutorial.com/pull/83.

Your changes are live at: https://www.markdowntutorial.com/nl/

If anything looks off, just feel free to send another PR. Thanks again!

**Pull request closed without merging**
