### PR TITLE
remove repeated word

### PR DESCRIPTION
**Pull request by snurolss**

### CODE REVIEW

**Comment by nicolasmccurdy** [comment]
I recommend rebasing this into one commit if possible.

**Comment by snurolss** [comment]
That's what I was trying to do but I don't understand how to do it. I don't have git installed, I just use the Github website because I noticed an error. Can you show me how to edit several files in one commit?

**Comment by gjtorikian** [comment]
Cool--thanks a bunch!

**Comment by gjtorikian** [comment]
To be clearer, I squashed the commits myself. @snurolss you might be interested in the following articles about merging commits into one:

* https://help.github.com/articles/about-git-rebase/
* https://help.github.com/articles/using-git-rebase/

It can't be done through GitHub's online interface, only the command line.

**Comment by nicolasmccurdy** [comment]
@snurolss This is unrelated to merging, but you can't edit multiple files in one commit on the GitHub website. I recommend using GitHub for Windows or GitHub for Mac, though you can also do that with more advanced tools like the git command line.

**Pull request merged**
