### PR TITLE
Fix issues in spanish translation

### PR DESCRIPTION
**Pull request by victorhck**
Fixed some typos, some issues in exercises, and updated lesson 4 for new imges

### CODE REVIEW

**Comment by gjtorikian** [comment]
Thanks!

**Comment by victorhck** [comment]
Don't know if something went wrong from my side...
The spanish text is right, but the spanish text in exercises is in english...

**Comment by victorhck** [comment]
A screenshot about the issue:

markdown_issue

The text is in spanish, but exercise is in english (and same in all lessons)

**Comment by gjtorikian** [comment]
Ah, yes, it's because of [this linebreak](https://github.com/gjtorikian/markdowntutorial.com/pull/68/files#diff-2728fe8bba5b67a28ba261888661a87dR61).

I've just pushed a fix, thank you for reporting!

**Comment by victorhck** [comment]
ups... sorry...

**Pull request merged**
