### PR TITLE
fix some issues in frech tutorial

### PR DESCRIPTION
**Pull request by victorhck**
I was testing french translation and found some issues.
I also found that in lesson 5, if you click the botton to jump to next lesson, you jump to lesson 5 again... but didn't found the place to fix it.

### CODE REVIEW

**Comment by victorhck** [comment]
I found where to fix the issue with lesson 6

**Comment by gjtorikian** [comment]
Merci! 🍰

**Comment by victorhck** [comment]
Can @Plumf please make a new review?
Thanks, gracias, merci! :)

**Comment by Plumf** [comment]
Excuse me, I just came back from summer camp and I haven't logged in for 15 days. Thank you for patch. I review this patch now.

**Pull request merged**
