### PR TITLE
Spanish translation

### PR DESCRIPTION
**Pull request by victorhck**
I have translated the files and lessons in Spanish for this tutorial.
The translation are in a locale/es folder.
I hope that can be useful. Can I help in other way? Can I have test this before be public? Just to test if everything it's Ok.
Greetings

### CODE REVIEW

**Comment by gjtorikian** [comment]
Oh! I have no idea how I missed this! I will take a look at it.

**Comment by victorhck** [comment]
ping @gjtorikian 
as reminder about this :)

**Comment by gjtorikian** [comment]
I am really, really sorry this took so long to review. I am going to merge and do a release tonight, I promise.

Thank you so much for this. I really appreciate it.

**Comment by gjtorikian** [comment]
By the way, do you have a preference for locale of this Spanish? ES from Spain, ES from Mexico, from Argentina, Colombia, etc?

**Comment by victorhck** [comment]
ES from Spain is rigth...

**Pull request merged**
